version: '3'
services:
  video-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NODE_PORT: 3000
      OPENAI_ORG_ID: org-fWGKS2alrGS0zVUM8UoxIiew
      OPENAI_API_KEY: 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
      REDIS_STRING: redis://default:4b0baaa6b8cc4e5b90401d18c5dbd7a0@us1-fitting-hare-41142.upstash.io:41142
      PINECONE_ENVIRONMENT: gcp-starter
      PINECONE_API_KEY: a12ab5f9-fd4c-4cf9-a93e-a534e7202ed8
